#! /bin/bash

export PS1='\w $ '
export CLICOLOR=1

if git --version >/dev/null 2>&1 && [ ! -f ~/.git-completion.bash ]; then
    curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash >/dev/null 2>&1
fi
test -f ~/.git-completion.bash && . ~/.git-completion.bash
